# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(null=True, verbose_name='create assessment date')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('file_path', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(null=True, verbose_name='added to library date')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='encoded_media_list',
            field=models.ManyToManyField(related_name='encoded_media_list', to='engine.Media'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='reference_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.Media'),
        ),
    ]
