# Generated by Django 2.0.1 on 2018-02-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='unnamed parameter', max_length=32)),
                ('value', models.CharField(max_length=32, null=True)),
                ('is_bool', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=280, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AppSettings',
        ),
    ]
