# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20170804_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
