# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_assessment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_path',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
