# Generated by Django 2.0.1 on 2018-02-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_chartannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartannotation',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='chartannotation',
            name='y',
            field=models.FloatField(null=True),
        ),
    ]
