# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import engine.utils


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20170808_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_library_path', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(null=True, upload_to=engine.utils.get_upload_path),
        ),
    ]
