# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20170929_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='average_bitrate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
