# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_assessment_chart_labels_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='chart_labels_path',
        ),
    ]
