# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_remove_assessment_chart_labels_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='framerate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='video_codec',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
