# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20171002_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='media',
            name='date_added',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_bitrate_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_probe_media',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='max_parallel_tasks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='worker_pulling_interval',
            field=models.IntegerField(default=10),
        ),
    ]
