# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20171005_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_generate_thumbnail',
            field=models.BooleanField(default=True),
        ),
    ]
