# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_appsettings_auto_generate_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='yuv_input_parameters',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
