# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_appsettings_yuv_input_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='yuv_input_parameters',
        ),
    ]
