# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('available_metrics', models.ManyToManyField(to='worker.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json_path', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(null=True, verbose_name='data insert date')),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Assessment')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Media')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, null=True)),
                ('date_queued', models.DateTimeField(null=True, verbose_name='date queued')),
                ('date_started', models.DateTimeField(null=True, verbose_name='date started')),
                ('date_last_update', models.DateTimeField(null=True, verbose_name='date last update')),
                ('date_complete', models.DateTimeField(null=True, verbose_name='date completed')),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Assessment')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.Media')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.Metric')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='worker.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.Task'),
        ),
    ]
