# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20170804_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.IntegerField(choices=[(0, 'Queued'), (1, 'Processing'), (2, 'Success'), (3, 'Error'), (4, 'Aborted')], default=0),
        ),
    ]
