# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auto_20170927_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
