# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_metric_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='available_metrics',
        ),
        migrations.RemoveField(
            model_name='task',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
