# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20170927_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='average_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='output_data_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
