# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_auto_20170928_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_last_update',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_queued',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_started',
        ),
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
