# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0009_auto_20170929_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='average_score',
            field=models.FloatField(null=True),
        ),
    ]
