# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0010_auto_20170929_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chart_labels_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
