# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0011_task_chart_labels_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_ended',
            field=models.DateTimeField(null=True, verbose_name='date ended'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_queued',
            field=models.DateTimeField(null=True, verbose_name='date queued'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_started',
            field=models.DateTimeField(null=True, verbose_name='date started'),
        ),
    ]
