# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_auto_20171004_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
    ]
