# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0013_auto_20171004_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='process_pid',
            field=models.IntegerField(null=True),
        ),
    ]
